### ISSUE TITLE
Request: include at:// URI in rel=alternate link header/tag

### ISSUE THREAD

**Issue by tom-sherman** [badlogic/skyview#13]
Described [here](https://bsky.app/profile/did:plc:2xau7wbgdq4phuou2ypwuen7/post/3l7esaih44s2s) and in https://github.com/likeandscribe/frontpage/pull/172

This is already supported in Bluesky, Frontpage, WhiteWind, and several blogs that use atproto as the storage layer. Adding in this extra piece of information greatly increases the connectivity of the atproto ecosystem as it allows tooling to pick up on the content in a semantic way.

The implementation is quite minimal and involves including the at:// URI in either a `<link>` tag or `Link` header in the initial server response.

Happy to open a PR to contribute this change, but let me know if you don't want to accept it of course

**Comment by tom-sherman** [comment]
I've just noticed that Skyview is currently an SPA but this request requires some server-side functionality. I don't know how feasible it is for you to add this, open to helping out in that larger technical effort if this is something you're open to pursuing.

**Comment by badlogic** [comment]
It's actually totally doable. The problem is that the at-uri would be the one the user submitted, which might not be the root of the thread. Getting to root of the thread would require lots of requests on the server side to the Bluesky servers, which I currently don't want to do. I'm also not sure if this would make semantic sense.
